//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoverYourself.Resources.Views.Reports {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AccumulationReport_tr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccumulationReport_tr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DiscoverYourself.Resources.Views.Reports.AccumulationReport_tr", typeof(AccumulationReport_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AccumulationReportMsg {
            get {
                return ResourceManager.GetString("AccumulationReportMsg", resourceCulture);
            }
        }
        
        internal static string DateMsg {
            get {
                return ResourceManager.GetString("DateMsg", resourceCulture);
            }
        }
        
        internal static string ActualCurrencyMsg {
            get {
                return ResourceManager.GetString("ActualCurrencyMsg", resourceCulture);
            }
        }
        
        internal static string TargetCurrencyMsg {
            get {
                return ResourceManager.GetString("TargetCurrencyMsg", resourceCulture);
            }
        }
        
        internal static string ActualGoldMsg {
            get {
                return ResourceManager.GetString("ActualGoldMsg", resourceCulture);
            }
        }
        
        internal static string TargetGoldMsg {
            get {
                return ResourceManager.GetString("TargetGoldMsg", resourceCulture);
            }
        }
        
        internal static string ActualSilverMsg {
            get {
                return ResourceManager.GetString("ActualSilverMsg", resourceCulture);
            }
        }
        
        internal static string TargetSilverMsg {
            get {
                return ResourceManager.GetString("TargetSilverMsg", resourceCulture);
            }
        }
    }
}
