//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoverYourself.Resources.Views.Reports {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EducationReport_tr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EducationReport_tr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DiscoverYourself.Resources.Views.Reports.EducationReport_tr", typeof(EducationReport_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EducationReportMsg {
            get {
                return ResourceManager.GetString("EducationReportMsg", resourceCulture);
            }
        }
        
        internal static string EndDateMsg {
            get {
                return ResourceManager.GetString("EndDateMsg", resourceCulture);
            }
        }
        
        internal static string StartDateMsg {
            get {
                return ResourceManager.GetString("StartDateMsg", resourceCulture);
            }
        }
        
        internal static string DescriptionMsg {
            get {
                return ResourceManager.GetString("DescriptionMsg", resourceCulture);
            }
        }
        
        internal static string DifficultyMsg {
            get {
                return ResourceManager.GetString("DifficultyMsg", resourceCulture);
            }
        }
        
        internal static string IsCompletedMsg {
            get {
                return ResourceManager.GetString("IsCompletedMsg", resourceCulture);
            }
        }
        
        internal static string MilestonesMsg {
            get {
                return ResourceManager.GetString("MilestonesMsg", resourceCulture);
            }
        }
        
        internal static string SuccessCriteriaMsg {
            get {
                return ResourceManager.GetString("SuccessCriteriaMsg", resourceCulture);
            }
        }
        
        internal static string TargetAudienceMsg {
            get {
                return ResourceManager.GetString("TargetAudienceMsg", resourceCulture);
            }
        }
        
        internal static string TitleMsg {
            get {
                return ResourceManager.GetString("TitleMsg", resourceCulture);
            }
        }
        
        internal static string TopicsMsg {
            get {
                return ResourceManager.GetString("TopicsMsg", resourceCulture);
            }
        }
    }
}
