//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoverYourself.Resources.Views.Home {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_tr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_tr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DiscoverYourself.Resources.Views.Home.Index_tr", typeof(Index_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string WelcomeMsg {
            get {
                return ResourceManager.GetString("WelcomeMsg", resourceCulture);
            }
        }
        
        internal static string AccumulationGoalsMsg {
            get {
                return ResourceManager.GetString("AccumulationGoalsMsg", resourceCulture);
            }
        }
        
        internal static string BusinessGoalsMsg {
            get {
                return ResourceManager.GetString("BusinessGoalsMsg", resourceCulture);
            }
        }
        
        internal static string DevelopmentGoalsMsg {
            get {
                return ResourceManager.GetString("DevelopmentGoalsMsg", resourceCulture);
            }
        }
        
        internal static string EducationGoalsMsg {
            get {
                return ResourceManager.GetString("EducationGoalsMsg", resourceCulture);
            }
        }
        
        internal static string LogoutMsg {
            get {
                return ResourceManager.GetString("LogoutMsg", resourceCulture);
            }
        }
        
        internal static string HomeMsg {
            get {
                return ResourceManager.GetString("HomeMsg", resourceCulture);
            }
        }
        
        internal static string ReportsMsg {
            get {
                return ResourceManager.GetString("ReportsMsg", resourceCulture);
            }
        }
        
        internal static string DiscoverYourselfMsg {
            get {
                return ResourceManager.GetString("DiscoverYourselfMsg", resourceCulture);
            }
        }
    }
}
