//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoverYourself.Resources.Views.Home {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Reports_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Reports_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DiscoverYourself.Resources.Views.Home.Reports_en", typeof(Reports_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AccumulationReportMsg {
            get {
                return ResourceManager.GetString("AccumulationReportMsg", resourceCulture);
            }
        }
        
        internal static string BusinessReportMsg {
            get {
                return ResourceManager.GetString("BusinessReportMsg", resourceCulture);
            }
        }
        
        internal static string EducationReportMsg {
            get {
                return ResourceManager.GetString("EducationReportMsg", resourceCulture);
            }
        }
        
        internal static string DevelopmentReportMsg {
            get {
                return ResourceManager.GetString("DevelopmentReportMsg", resourceCulture);
            }
        }
        
        internal static string AccumulationReportDesc {
            get {
                return ResourceManager.GetString("AccumulationReportDesc", resourceCulture);
            }
        }
        
        internal static string EducationReportDesc {
            get {
                return ResourceManager.GetString("EducationReportDesc", resourceCulture);
            }
        }
        
        internal static string DevelopmentReportDesc {
            get {
                return ResourceManager.GetString("DevelopmentReportDesc", resourceCulture);
            }
        }
        
        internal static string BusinessReportDesc {
            get {
                return ResourceManager.GetString("BusinessReportDesc", resourceCulture);
            }
        }
        
        internal static string WelcomeToYourReportsMsg {
            get {
                return ResourceManager.GetString("WelcomeToYourReportsMsg", resourceCulture);
            }
        }
    }
}
