//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoverYourself.Resources.Views.AccumulationGoals {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DiscoverYourself.Resources.Views.AccumulationGoals.Index_en", typeof(Index_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AccumulationGoalsMsg {
            get {
                return ResourceManager.GetString("AccumulationGoalsMsg", resourceCulture);
            }
        }
        
        internal static string DateMsg {
            get {
                return ResourceManager.GetString("DateMsg", resourceCulture);
            }
        }
        
        internal static string GoalsMsg {
            get {
                return ResourceManager.GetString("GoalsMsg", resourceCulture);
            }
        }
        
        internal static string TargetCurrencyMsg {
            get {
                return ResourceManager.GetString("TargetCurrencyMsg", resourceCulture);
            }
        }
        
        internal static string TargetGoldMsg {
            get {
                return ResourceManager.GetString("TargetGoldMsg", resourceCulture);
            }
        }
        
        internal static string TargetSilverMsg {
            get {
                return ResourceManager.GetString("TargetSilverMsg", resourceCulture);
            }
        }
        
        internal static string RealizedMsg {
            get {
                return ResourceManager.GetString("RealizedMsg", resourceCulture);
            }
        }
        
        internal static string RealizedCurrencyMsg {
            get {
                return ResourceManager.GetString("RealizedCurrencyMsg", resourceCulture);
            }
        }
        
        internal static string RealizedGoldMsg {
            get {
                return ResourceManager.GetString("RealizedGoldMsg", resourceCulture);
            }
        }
        
        internal static string RealizedSilverMsg {
            get {
                return ResourceManager.GetString("RealizedSilverMsg", resourceCulture);
            }
        }
        
        internal static string SaveMsg {
            get {
                return ResourceManager.GetString("SaveMsg", resourceCulture);
            }
        }
        
        internal static string UpdateChartMsg {
            get {
                return ResourceManager.GetString("UpdateChartMsg", resourceCulture);
            }
        }
        
        internal static string GoldMsg {
            get {
                return ResourceManager.GetString("GoldMsg", resourceCulture);
            }
        }
        
        internal static string SilverMsg {
            get {
                return ResourceManager.GetString("SilverMsg", resourceCulture);
            }
        }
        
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
    }
}
